MtMoon_B2F_Text_MiguelIntro::
    .string "Godammit!\p"
    .string "You meddling brat!\p"
    .string "These fossils are the propety\n"
    .string "of TEAM ROCKET!\p"
    .string "I'll teach you a lesson!$"

MtMoon_B2F_Text_MiguelDefeat::
    .string "Damn! The boss will not\n"
    .string "be happy to hear this...$"

MtMoon_B2F_Text_Grunt1Intro::
    .string "We, TEAM ROCKET, shall have the\n"
    .string "fossils!\p"
    .string "Reviving POKéMON from them will\n"
    .string "earn us huge riches!$"

MtMoon_B2F_Text_Grunt1Defeat::
    .string "Urgh!\n"
    .string "Now I'm mad!$"

MtMoon_B2F_Text_Grunt1PostBattle::
    .string "You made me mad!\n"
    .string "TEAM ROCKET will blacklist you!$"

MtMoon_B2F_Text_Grunt2Intro::
    .string "We, TEAM ROCKET, are POKéMON\n"
    .string "gangsters!\l"
    .string "We strike fear with our strength!$"

MtMoon_B2F_Text_Grunt2Defeat::
    .string "I blew it!$"

MtMoon_B2F_Text_Grunt2PostBattle::
    .string "Darn it all!\n"
    .string "My associates won't stand for this!$"

MtMoon_B2F_Text_Grunt3Intro::
    .string "We're pulling a big job here!\n"
    .string "Get lost, kid!$"

MtMoon_B2F_Text_Grunt3Defeat::
    .string "So, you are good…$"

MtMoon_B2F_Text_Grunt3PostBattle::
    .string "Piss off, kid!$"

MtMoon_B2F_Text_Grunt4Intro::
    .string "Little kids shouldn't be messing\n"
    .string "around with grown-ups!\p"
    .string "It could be bad news!$"

MtMoon_B2F_Text_Grunt4Defeat::
    .string "I'm steamed!$"

MtMoon_B2F_Text_Grunt4PostBattle::
    .string "POKéMON lived here long before\n"
    .string "people came.$"

MtMoon_B2F_Text_YouWantDomeFossil::
    .string "Do you want the DOME FOSSIL?$"

MtMoon_B2F_Text_YouWantHelixFossil::
    .string "Do you want the HELIX FOSSIL?$"

MtMoon_B2F_Text_ObtainedHelixFossil::
    .string "Obtained the HELIX FOSSIL!$"

MtMoon_B2F_Text_ObtainedDomeFossil::
    .string "Obtained the DOME FOSSIL!$"

MtMoon_B2F_Text_BenIntro::
    .string "Watch out for GEODUDE!\p"
    .string "They like to blow up!$"

MtMoon_B2F_Text_BenDefeat::
    .string "Hahaha! What a battle!\n"
    .string "Got me cranking my shiii!$"

MtMoon_B2F_Text_BenGiveSunStone::
    .string "That was fun. I demand a proper\n"
    .string "rematch next time we meet!\p"
    .string "Here, I found this but doubt I\n"
    .string "will use it.$"

MtMoon_B2F_Text_BenAfterGift::
    .string "Alright, I'm outta here!\n"
    .string "Gonna go heal up at the POKéMON\p"
    .string "center.$"
